formspree_form_id: formspree_form_id
name: Patrick Medley
title: "| A personal portfolio website and more"
description: A personal portfolio website of Patrick Medley
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: patrickm@pgmja.com
disqus_username: ""
